### ISSUE TITLE
Add alternatives to tools

### ISSUE THREAD

**Issue by trentonyo** [Start-Out/golden-paths#18]
For example, say that a tool (git-hooks) uses Git 2.9.0 and the user does not want to change their Git version. The Starterfile may look like:

```

tools:
  git-hooks:
    alt: git-hooks-py
    scripts:
      check: git --version # | semver xxx
      install: git config ...
      destroy: git config ...
  git-hooks-py:
    check: python --version
    install: python ./scripts/install-git-hooks.py

```

Allowing for fallback version of tools
